# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uid_management.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uid_management.proto',
  package='uidmanagement',
  syntax='proto3',
  serialized_options=_b('\n\036io.grpc.examples.uidmanagementB\022UidManagementProtoP\001\242\002\004UIDM'),
  serialized_pb=_b('\n\x14uid_management.proto\x12\ruidmanagement\"\x1d\n\tIpAddress\x12\x10\n\x08\x63lientIp\x18\x01 \x01(\t\"\x12\n\x03Uid\x12\x0b\n\x03uid\x18\x01 \x01(\t\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8a\x01\n\rUidManagement\x12\x38\n\x06GetUid\x12\x18.uidmanagement.IpAddress\x1a\x12.uidmanagement.Uid\"\x00\x12?\n\x11TransferCompleted\x12\x11.uidmanagement.Id\x1a\x15.uidmanagement.Status\"\x00\x42=\n\x1eio.grpc.examples.uidmanagementB\x12UidManagementProtoP\x01\xa2\x02\x04UIDMb\x06proto3')
)




_IPADDRESS = _descriptor.Descriptor(
  name='IpAddress',
  full_name='uidmanagement.IpAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientIp', full_name='uidmanagement.IpAddress.clientIp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=68,
)


_UID = _descriptor.Descriptor(
  name='Uid',
  full_name='uidmanagement.Uid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='uidmanagement.Uid.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=88,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='uidmanagement.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='uidmanagement.Id.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=106,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='uidmanagement.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='uidmanagement.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['IpAddress'] = _IPADDRESS
DESCRIPTOR.message_types_by_name['Uid'] = _UID
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IpAddress = _reflection.GeneratedProtocolMessageType('IpAddress', (_message.Message,), {
  'DESCRIPTOR' : _IPADDRESS,
  '__module__' : 'uid_management_pb2'
  # @@protoc_insertion_point(class_scope:uidmanagement.IpAddress)
  })
_sym_db.RegisterMessage(IpAddress)

Uid = _reflection.GeneratedProtocolMessageType('Uid', (_message.Message,), {
  'DESCRIPTOR' : _UID,
  '__module__' : 'uid_management_pb2'
  # @@protoc_insertion_point(class_scope:uidmanagement.Uid)
  })
_sym_db.RegisterMessage(Uid)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'uid_management_pb2'
  # @@protoc_insertion_point(class_scope:uidmanagement.Id)
  })
_sym_db.RegisterMessage(Id)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'uid_management_pb2'
  # @@protoc_insertion_point(class_scope:uidmanagement.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_UIDMANAGEMENT = _descriptor.ServiceDescriptor(
  name='UidManagement',
  full_name='uidmanagement.UidManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUid',
    full_name='uidmanagement.UidManagement.GetUid',
    index=0,
    containing_service=None,
    input_type=_IPADDRESS,
    output_type=_UID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransferCompleted',
    full_name='uidmanagement.UidManagement.TransferCompleted',
    index=1,
    containing_service=None,
    input_type=_ID,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UIDMANAGEMENT)

DESCRIPTOR.services_by_name['UidManagement'] = _UIDMANAGEMENT

# @@protoc_insertion_point(module_scope)
